import { FormEvent, useEffect, useState } from "react";
import { Activity, AlertCircle, ArrowRight, BarChart3, Bell, CheckCircle2, ChevronRight, ClipboardList, Clock3, FilePlus2, Filter, LayoutDashboard, LogOut, MapPin, MessageSquare, Plus, Search, ShieldCheck, Star, UserRound, X } from "lucide-react";
import { api } from "./api";
import { Dashboard, Occurrence, Priority, Role, Status, User } from "./types";

const statusLabel: Record<Status, string> = { ABERTA: "Aberta", EM_ANALISE: "Em análise", EM_ATENDIMENTO: "Em atendimento", RESOLVIDA: "Resolvida", CANCELADA: "Cancelada" };
const priorityLabel: Record<Priority, string> = { BAIXA: "Baixa", MEDIA: "Média", ALTA: "Alta", URGENTE: "Urgente" };
const categories = ["Iluminação", "Manutenção", "Limpeza", "Segurança", "Acessibilidade", "Vazamento", "Outro"];
const statuses: Status[] = ["ABERTA", "EM_ANALISE", "EM_ATENDIMENTO", "RESOLVIDA", "CANCELADA"];

function formatDate(value: string) { return new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function initials(name: string) { return name.split(" ").map((part) => part[0]).slice(0, 2).join("").toUpperCase(); }

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [authMode, setAuthMode] = useState<"login" | "register">("login");
  const [view, setView] = useState<"overview" | "occurrences" | "dashboard">("overview");
  const [occurrences, setOccurrences] = useState<Occurrence[]>([]);
  const [dashboard, setDashboard] = useState<Dashboard | null>(null);
  const [selected, setSelected] = useState<Occurrence | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => { const saved = localStorage.getItem("resolve-ai-user"); if (saved) setUser(JSON.parse(saved)); }, []);
  useEffect(() => { if (user) refresh(); }, [user, view]);
  async function refresh() { try { setLoading(true); const result = await api.occurrences(); setOccurrences(result.data); if (user?.role === "GESTOR") setDashboard(await api.dashboard()); } catch (err) { setError(err instanceof Error ? err.message : "Erro ao carregar dados"); } finally { setLoading(false); } }
  function finishAuth(nextUser: User, token: string) { localStorage.setItem(api.tokenKey, token); localStorage.setItem("resolve-ai-user", JSON.stringify(nextUser)); setUser(nextUser); }
  function logout() { localStorage.removeItem(api.tokenKey); localStorage.removeItem("resolve-ai-user"); setUser(null); setOccurrences([]); }
  if (!user) return <AuthScreen mode={authMode} setMode={setAuthMode} onSuccess={finishAuth} />;

  const openCount = occurrences.filter((item) => !["RESOLVIDA", "CANCELADA"].includes(item.status)).length;
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Activity size={20} /></span><span>resolve<span>ai</span></span></div>
      <div className="workspace-label">CENTRAL DE OCORRÊNCIAS</div>
      <nav>
        <button className={view === "overview" ? "nav-item active" : "nav-item"} onClick={() => setView("overview")}><LayoutDashboard size={18} /> Visão geral</button>
        <button className={view === "occurrences" ? "nav-item active" : "nav-item"} onClick={() => setView("occurrences")}><ClipboardList size={18} /> Ocorrências <span className="nav-count">{openCount}</span></button>
        {user.role === "GESTOR" && <button className={view === "dashboard" ? "nav-item active" : "nav-item"} onClick={() => setView("dashboard")}><BarChart3 size={18} /> Indicadores</button>}
      </nav>
      <div className="sidebar-foot"><div className="tip"><ShieldCheck size={18} /><div><strong>Ambiente protegido</strong><small>Seus registros estão seguros.</small></div></div><button className="logout" onClick={logout}><LogOut size={16} /> Sair</button></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="breadcrumb">Resolve Aí <ChevronRight size={14} /> <strong>{view === "dashboard" ? "Indicadores" : view === "occurrences" ? "Ocorrências" : "Visão geral"}</strong></div><div className="top-actions"><button className="icon-button" title="Notificações"><Bell size={19} /><i /></button><div className="user-menu"><span className="avatar">{initials(user.name)}</span><div><strong>{user.name}</strong><small>{user.role === "GESTOR" ? "Gestor" : "Solicitante"}</small></div></div></div></header>
      <div className="content-wrap">
        {error && <div className="error-banner"><AlertCircle size={17} /> {error}<button onClick={() => setError("")}><X size={15} /></button></div>}
        {view === "overview" && <Overview user={user} occurrences={occurrences} dashboard={dashboard} onCreate={() => setShowCreate(true)} onSelect={setSelected} onAll={() => setView("occurrences")} />}
        {view === "occurrences" && <OccurrenceList occurrences={occurrences} loading={loading} user={user} onCreate={() => setShowCreate(true)} onSelect={setSelected} />}
        {view === "dashboard" && <ManagerDashboard dashboard={dashboard} occurrences={occurrences} />}
      </div>
    </main>
    {showCreate && <CreateModal onClose={() => setShowCreate(false)} onCreated={() => { setShowCreate(false); refresh(); }} />}
    {selected && <DetailModal occurrence={selected} user={user} onClose={() => setSelected(null)} onUpdated={() => { setSelected(null); refresh(); }} />}
  </div>;
}

function AuthScreen({ mode, setMode, onSuccess }: { mode: "login" | "register"; setMode: (mode: "login" | "register") => void; onSuccess: (user: User, token: string) => void }) {
  const [form, setForm] = useState({ name: "", email: "", password: "", role: "SOLICITANTE" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = mode === "login" ? await api.login({ email: form.email, password: form.password }) : await api.register(form); onSuccess(result.user, result.token); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível entrar"); } finally { setBusy(false); } }
  return <div className="auth-page"><div className="auth-decoration"><div className="deco-grid" /><div className="auth-copy"><div className="brand light"><span className="brand-mark"><Activity size={20} /></span><span>resolve<span>ai</span></span></div><p className="eyebrow">GESTÃO QUE SE MOVE</p><h1>O problema aparece.<br /><em>A solução também.</em></h1><p className="auth-description">Registre, acompanhe e resolva ocorrências com clareza do começo ao fim.</p><div className="auth-proof"><div className="proof-icon"><CheckCircle2 size={18} /></div><span>Fluxo rastreável e transparente</span></div></div><div className="auth-orbit orbit-one" /><div className="auth-orbit orbit-two" /></div><div className="auth-panel"><div className="mobile-brand brand"><span className="brand-mark"><Activity size={20} /></span><span>resolve<span>ai</span></span></div><div className="auth-form"><div className="form-heading"><span className="section-kicker">BEM-VINDO</span><h2>{mode === "login" ? "Acesse seu painel" : "Crie sua conta"}</h2><p>{mode === "login" ? "Entre para acompanhar o que precisa ser resolvido." : "Comece a organizar suas ocorrências."}</p></div><form onSubmit={submit}>{mode === "register" && <label>Nome completo<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Como podemos chamar você?" required /></label>}<label>E-mail<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="voce@exemplo.com" required /></label><label>Senha<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Mínimo de 6 caracteres" required /></label>{mode === "register" && <label>Perfil<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="SOLICITANTE">Solicitante</option><option value="GESTOR">Gestor</option></select></label>}{error && <div className="form-error"><AlertCircle size={16} /> {error}</div>}<button className="primary-button full" disabled={busy}>{busy ? "Aguarde..." : mode === "login" ? "Entrar no painel" : "Criar minha conta"}<ArrowRight size={17} /></button></form><p className="switch-auth">{mode === "login" ? "Ainda não tem uma conta?" : "Já possui uma conta?"} <button onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }}>{mode === "login" ? "Cadastre-se" : "Fazer login"}</button></p></div><span className="auth-footer">Resolve Aí · Plataforma de Gestão de Ocorrências</span></div></div>;
}

function Overview({ user, occurrences, dashboard, onCreate, onSelect, onAll }: { user: User; occurrences: Occurrence[]; dashboard: Dashboard | null; onCreate: () => void; onSelect: (item: Occurrence) => void; onAll: () => void }) {
  const active = occurrences.filter((item) => !["RESOLVIDA", "CANCELADA"].includes(item.status)); const resolved = occurrences.filter((item) => item.status === "RESOLVIDA");
  return <><div className="page-intro"><div><span className="section-kicker">{user.role === "GESTOR" ? "CENTRAL DE CONTROLE" : "SEU ESPAÇO"}</span><h1>Olá, {user.name.split(" ")[0]} <span className="wave">✦</span></h1><p>{user.role === "GESTOR" ? "Aqui está o panorama das ocorrências da sua operação." : "Acompanhe de perto cada solicitação feita por você."}</p></div><button className="primary-button" onClick={onCreate}><Plus size={18} /> Nova ocorrência</button></div><div className="metrics-grid"><Metric icon={<ClipboardList />} label="Total de ocorrências" value={occurrences.length} tone="blue" /><Metric icon={<Clock3 />} label="Em andamento" value={active.length} tone="amber" /><Metric icon={<CheckCircle2 />} label="Resolvidas" value={resolved.length} tone="green" /><Metric icon={<Star />} label="Avaliação média" value={dashboard?.averageRating ? dashboard.averageRating.toFixed(1) : "—"} tone="violet" /></div><section className="section-block"><div className="section-header"><div><h2>Atividade recente</h2><p>As últimas ocorrências registradas no sistema</p></div><button className="text-button" onClick={onAll}>Ver todas <ArrowRight size={16} /></button></div><OccurrenceTable occurrences={occurrences.slice(0, 5)} onSelect={onSelect} /></section></>;
}
function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string | number; tone: string }) { return <div className="metric-card"><div className={`metric-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong></div><div className="metric-spark" /></div>; }

function OccurrenceList({ occurrences, loading, user, onCreate, onSelect }: { occurrences: Occurrence[]; loading: boolean; user: User; onCreate: () => void; onSelect: (item: Occurrence) => void }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const filtered = occurrences.filter((item) => `${item.title} ${item.category} ${item.location}`.toLowerCase().includes(query.toLowerCase()) && (!status || item.status === status));
  return <><div className="page-intro"><div><span className="section-kicker">REGISTROS</span><h1>{user.role === "GESTOR" ? "Todas as ocorrências" : "Minhas ocorrências"}</h1><p>{occurrences.length} registros encontrados para acompanhamento.</p></div><button className="primary-button" onClick={onCreate}><Plus size={18} /> Nova ocorrência</button></div><div className="filter-bar"><div className="search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por título, categoria ou local..." /></div><div className="filter-select"><Filter size={16} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Todos os status</option>{statuses.map((item) => <option key={item} value={item}>{statusLabel[item]}</option>)}</select></div></div>{loading ? <div className="empty-state"><Activity className="spin" /><p>Carregando ocorrências...</p></div> : <OccurrenceTable occurrences={filtered} onSelect={onSelect} />}</>;
}
function OccurrenceTable({ occurrences, onSelect }: { occurrences: Occurrence[]; onSelect: (item: Occurrence) => void }) { return <div className="table-wrap"><table><thead><tr><th>Ocorrência</th><th>Categoria</th><th>Prioridade</th><th>Status</th><th>Atualizada</th><th /></tr></thead><tbody>{occurrences.map((item) => <tr key={item.id} onClick={() => onSelect(item)}><td><div className="issue-title"><span className="issue-dot" /> <div><strong>{item.title}</strong><small>#{item.id.slice(0, 8)}</small></div></div></td><td><span className="category-text">{item.category}</span></td><td><span className={`priority ${item.priority.toLowerCase()}`}>{priorityLabel[item.priority]}</span></td><td><span className={`status-pill ${item.status.toLowerCase()}`}><i />{statusLabel[item.status]}</span></td><td className="date-cell">{formatDate(item.updatedAt)}</td><td><ChevronRight className="row-arrow" size={17} /></td></tr>)}</tbody></table>{!occurrences.length && <div className="empty-state"><ClipboardList size={28} /><strong>Nenhuma ocorrência encontrada</strong><p>Os registros aparecerão aqui assim que forem criados.</p></div>}</div>; }

function ManagerDashboard({ dashboard, occurrences }: { dashboard: Dashboard | null; occurrences: Occurrence[] }) { if (!dashboard) return <div className="empty-state"><Activity className="spin" /><p>Carregando indicadores...</p></div>; const max = Math.max(...Object.values(dashboard.byStatus), 1); return <><div className="page-intro"><div><span className="section-kicker">INTELIGÊNCIA OPERACIONAL</span><h1>Indicadores</h1><p>Uma leitura rápida da saúde da sua operação.</p></div><div className="date-chip"><Clock3 size={16} /> Atualizado agora</div></div><div className="dashboard-grid"><div className="dash-card wide"><div className="card-heading"><div><h3>Fluxo das ocorrências</h3><p>Distribuição por etapa do atendimento</p></div><BarChart3 size={21} /></div><div className="bar-chart">{statuses.map((status) => <div className="bar-column" key={status}><span>{dashboard.byStatus[status]}</span><div className="bar-track"><div className={`bar-fill ${status.toLowerCase()}`} style={{ height: `${Math.max((dashboard.byStatus[status] / max) * 100, dashboard.byStatus[status] ? 12 : 4)}%` }} /></div><small>{statusLabel[status].replace("Em ", "")}</small></div>)}</div></div><div className="dash-card"><div className="card-heading"><div><h3>Prioridades</h3><p>Demandas por urgência</p></div><AlertCircle size={21} /></div><div className="priority-list">{(Object.keys(dashboard.byPriority) as Priority[]).map((priority) => <div className="priority-row" key={priority}><span><i className={`priority-dot ${priority.toLowerCase()}`} />{priorityLabel[priority]}</span><strong>{dashboard.byPriority[priority]}</strong></div>)}</div></div><div className="dash-card"><div className="card-heading"><div><h3>Resumo geral</h3><p>Qualidade percebida</p></div><Star size={21} /></div><div className="rating-big">{dashboard.averageRating ? dashboard.averageRating.toFixed(1) : "—"}<span>/ 5</span></div><div className="rating-stars">★★★★★</div><p className="muted">Baseado nas avaliações recebidas</p></div><div className="dash-card wide recent-card"><div className="card-heading"><div><h3>Últimos registros</h3><p>Ocorrências que exigem atenção</p></div><ClipboardList size={21} /></div><div className="mini-list">{occurrences.slice(0, 4).map((item) => <div className="mini-row" key={item.id}><span className={`status-indicator ${item.status.toLowerCase()}`} /><div><strong>{item.title}</strong><small>{item.category} · {formatDate(item.updatedAt)}</small></div><span className={`status-pill ${item.status.toLowerCase()}`}><i />{statusLabel[item.status]}</span></div>)}</div></div></div></>; }

function CreateModal({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) { const [form, setForm] = useState({ title: "", description: "", category: categories[0], location: "", priority: "MEDIA" as Priority }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api.createOccurrence(form); onCreated(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível criar a ocorrência"); } finally { setBusy(false); } } return <Modal title="Nova ocorrência" subtitle="Descreva o que precisa ser resolvido." onClose={onClose}><form className="modal-form" onSubmit={submit}><label>Título<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Ex.: Lâmpada queimada no corredor" required /></label><div className="form-row"><label>Categoria<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Prioridade<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as Priority })}>{Object.keys(priorityLabel).map((item) => <option key={item} value={item}>{priorityLabel[item as Priority]}</option>)}</select></label></div><label>Localização<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="Ex.: Bloco B, 2º andar" required /></label><label>Descrição<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Conte os detalhes para facilitar o atendimento..." rows={4} required /></label>{error && <div className="form-error"><AlertCircle size={16} /> {error}</div>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={busy}><FilePlus2 size={17} />{busy ? "Registrando..." : "Registrar ocorrência"}</button></div></form></Modal>; }

function DetailModal({ occurrence, user, onClose, onUpdated }: { occurrence: Occurrence; user: User; onClose: () => void; onUpdated: () => void }) { const [comment, setComment] = useState(""); const [status, setStatus] = useState(occurrence.status); const [solution, setSolution] = useState(occurrence.solution || ""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function save() { setBusy(true); try { if (user.role === "GESTOR") await api.updateOccurrence(occurrence.id, { status, solution }); if (comment) await api.comment(occurrence.id, comment); onUpdated(); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível atualizar"); } finally { setBusy(false); } } return <Modal title={occurrence.title} subtitle={`Registrada em ${formatDate(occurrence.createdAt)}`} onClose={onClose}><div className="detail-meta"><span className={`status-pill ${occurrence.status.toLowerCase()}`}><i />{statusLabel[occurrence.status]}</span><span className={`priority ${occurrence.priority.toLowerCase()}`}>{priorityLabel[occurrence.priority]}</span><span><MapPin size={14} /> {occurrence.location}</span></div><div className="detail-description"><span className="section-kicker">DESCRIÇÃO</span><p>{occurrence.description}</p></div>{occurrence.history.length > 0 && <div className="timeline"><span className="section-kicker">HISTÓRICO</span>{occurrence.history.map((entry) => <div className="timeline-row" key={entry.id}><span className="timeline-dot" /><div><strong>{statusLabel[entry.newStatus]}</strong><small>{formatDate(entry.changedAt)} {entry.note ? `· ${entry.note}` : ""}</small></div></div>)}</div>}<div className="comments-area"><span className="section-kicker"><MessageSquare size={13} /> COMENTÁRIOS</span>{occurrence.comments.length ? occurrence.comments.map((item) => <div className="comment" key={item.id}><span className="avatar small">{initials(user.name)}</span><div><p>{item.text}</p><small>{formatDate(item.createdAt)}</small></div></div>) : <p className="muted">Ainda não há comentários.</p>}</div>{user.role === "GESTOR" && <div className="manager-edit"><label>Status<select value={status} onChange={(e) => setStatus(e.target.value as Status)}>{statuses.map((item) => <option key={item} value={item}>{statusLabel[item]}</option>)}</select></label><label>Solução aplicada<textarea value={solution} onChange={(e) => setSolution(e.target.value)} placeholder="Descreva a solução..." rows={2} /></label></div>}<label className="comment-input"><span>Adicionar comentário</span><textarea value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Escreva uma atualização..." rows={2} /></label>{error && <div className="form-error"><AlertCircle size={16} /> {error}</div>}<div className="modal-actions"><button className="secondary-button" onClick={onClose}>Fechar</button><button className="primary-button" onClick={save} disabled={busy}>{busy ? "Salvando..." : "Salvar atualização"}</button></div></Modal>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><div className="modal"><div className="modal-header"><div><span className="section-kicker">RESOLVE AÍ</span><h2>{title}</h2><p>{subtitle}</p></div><button className="close-button" onClick={onClose}><X size={19} /></button></div>{children}</div></div>; }
